apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ghkimdev/account:1.0.0-89
          ports:
            - containerPort: 8080
